import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/mongodb";
import { getAuthFromCookies } from "@/lib/auth";
import { ObjectId } from "mongodb";
import Anthropic from "@anthropic-ai/sdk";
import mammoth from "mammoth";

export const maxDuration = 60;

/**
 * Extract text from a PDF buffer using pdfjs-dist (server-side, no canvas).
 */
async function extractPdfText(buffer: Buffer): Promise<string> {
  // Dynamic import to avoid issues with Next.js bundling
  const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");

  const data = new Uint8Array(buffer);
  const doc = await pdfjsLib.getDocument({ data, useSystemFonts: true }).promise;

  const pages: string[] = [];
  for (let i = 1; i <= Math.min(doc.numPages, 50); i++) {
    const page = await doc.getPage(i);
    const textContent = await page.getTextContent();
    const pageText = textContent.items
      .map((item) => ("str" in item ? (item as { str: string }).str : ""))
      .join(" ");
    pages.push(pageText);
  }

  return pages.join("\n\n");
}

/**
 * Extract text from a DOCX buffer using mammoth.
 */
async function extractDocxText(buffer: Buffer): Promise<string> {
  const result = await mammoth.extractRawText({ buffer });
  return result.value;
}

/**
 * POST /api/review/analyze-citations
 *
 * Body: { paperId: string, reviewContent: string }
 *
 * Extracts text from the uploaded paper, then asks Claude to:
 * 1. Identify which citations/references from the paper should be used in the review
 * 2. Check whether existing citations in the review are used properly
 */
export async function POST(req: NextRequest) {
  const auth = await getAuthFromCookies();
  if (!auth) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let paperId: string;
  let reviewContent: string;

  try {
    const body = await req.json();
    paperId = body.paperId;
    reviewContent = body.reviewContent;
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  if (!paperId || !reviewContent) {
    return NextResponse.json(
      { error: "paperId and reviewContent are required" },
      { status: 400 }
    );
  }

  if (!ObjectId.isValid(paperId)) {
    return NextResponse.json({ error: "Invalid paper ID" }, { status: 400 });
  }

  // Fetch paper from DB
  const db = await getDb();
  const paper = await db.collection("papers").findOne({
    _id: new ObjectId(paperId),
    userId: auth.userId,
  });

  if (!paper) {
    return NextResponse.json({ error: "Paper not found" }, { status: 404 });
  }

  // Extract text from the paper
  let paperText: string;
  try {
    const buf = paper.content.buffer
      ? Buffer.from(paper.content.buffer)
      : Buffer.from(paper.content);

    if (paper.mimeType === "application/pdf") {
      paperText = await extractPdfText(buf);
    } else if (
      paper.mimeType ===
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ) {
      paperText = await extractDocxText(buf);
    } else {
      return NextResponse.json(
        { error: "Unsupported file type" },
        { status: 400 }
      );
    }
  } catch (error) {
    console.error("Text extraction error:", error);
    return NextResponse.json(
      { error: "Failed to extract text from the paper" },
      { status: 500 }
    );
  }

  if (!paperText || paperText.trim().length < 50) {
    return NextResponse.json(
      { error: "Could not extract meaningful text from this paper. The PDF may be image-based." },
      { status: 422 }
    );
  }

  // Truncate to avoid token limits (~40k chars ≈ ~10k tokens)
  const truncatedPaperText = paperText.substring(0, 40000);
  const truncatedReview = reviewContent.substring(0, 20000);

  // Ask Claude to analyze citations
  const client = new Anthropic();

  try {
    const response = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 4096,
      system: `You are an expert academic citation analyst. You will be given:
1. The full text of a user's paper (the "dropped paper")
2. A literature review that was generated by the system

Your job is to analyze how the dropped paper's citations and references relate to the literature review. Provide a structured analysis in the following format:

## Citation Analysis for "{filename}"

### Suggested Citations to Add
List references from the dropped paper that are relevant to the literature review but are NOT currently cited in it. For each one, explain briefly why it would strengthen the review and where it could fit.

### Existing Citations Review
Check the citations already used in the literature review. For each one that also appears in the dropped paper, assess:
- Whether it is cited accurately (correct authors, year, claims attributed)
- Whether the citation is used in the right context
- Any concerns about misrepresentation or over-generalization

### Overlapping References
List any references that appear in BOTH the dropped paper and the literature review. Note whether they are used consistently.

### Summary
A brief 2-3 sentence overall assessment of citation quality and recommendations.

Be specific and scholarly. Reference actual paper titles, authors, and years whenever possible.`,
      messages: [
        {
          role: "user",
          content: `Here is the literature review:\n\n---\n${truncatedReview}\n---\n\nHere is the full text of the dropped paper ("${paper.filename}"):\n\n---\n${truncatedPaperText}\n---\n\nPlease analyze the citations as described.`,
        },
      ],
    });

    const analysisText = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n");

    return NextResponse.json({
      analysis: analysisText,
      paperFilename: paper.filename,
    });
  } catch (error) {
    console.error("Claude citation analysis error:", error);
    return NextResponse.json(
      { error: "Failed to analyze citations" },
      { status: 500 }
    );
  }
}
